### ISSUE TITLE
HIDE_ATTRIBUTES does not work anymore

### ISSUE THREAD

**Issue by LordRazen** [promcteam/BossShopPro#105]
Before Minecraft 1.20.6, you could use `hideflags:HIDE_ATTRIBUTES` to hide attributes from an item. 

This does not work anymore. I guess it has to do with the many changes under the hood in Minecraft like renamed attributes etc.

---

Server Version: purpur-1.21.1-2308.jar
Plugin Version: genesis-1.0.1-R0.4-20241006.023017-1.jar

---

**Before Minecraft 1.20.6**
![grafik](https://github.com/user-attachments/assets/150c378c-90c4-48f7-a7bb-128e7e02a5d9)

**After Minecraft 1.20.6**
![grafik](https://github.com/user-attachments/assets/b7744436-df24-4d82-8752-2c3f5dbe062b)

**Config**
```
    MenuItem: 
    - type:WOOD_AXE
    - enchantment:efficiency#5
    - hideflags:HIDE_ATTRIBUTES
    - 'name:&4Holzaxt des Schaffens'
    - 'lore:&7Ein legendäres Werkzeug#&7mit dessen Hilft Blockhaim#&7erbaut wurde!'
    RewardType: item
    Reward: 
    - type:WOOD_AXE
    - enchantment:efficiency#5
    - hideflags:HIDE_ATTRIBUTES
    - 'name:&4Holzaxt des Schaffens'
    - 'lore:&7Ein legendäres Werkzeug#&7mit dessen Hilft Blockhaim#&7erbaut wurde!'
    Message: '&6[&4Info&6] &aHerzlichen Glückwunsch! Du hast einen Schatz gefunden!'
```
