### ISSUE TITLE
Item Price does not work anymore

### ISSUE THREAD

**Issue by LordRazen** [promcteam/BossShopPro#127]
Versions: 
genesis-1.0.2-R0.18-20250301.054712-1.jar
purpur-1.21.4-2398.jar

```
  komprimierte_erde: 
    InventoryLocation: 20
    MenuItem: 
    - type:DIRT
    - amount:64
    - 'name:&aKomprimierte Erde'
    PriceType: item
    Price: 
    - type:DIRT
    - amount:576
    RewardType: command
    Reward: 
    - hdb give custom5-12 1 %player%
```

This used to work in 1.21, but doesnt work in 1.21.4 anymore -  I always have to less items in my inventory: 

![Image](https://github.com/user-attachments/assets/f588ab3a-0936-4eb1-b906-b4d2d023f640)
