### ISSUE TITLE
[Suggestion] Empty slots

### ISSUE THREAD

**Issue by ga6rielsilva** [promcteam/BossShopPro#28]
Adding an option (InventoryFill) that allows you to fill empty slots with certain items would make the setup much better:

Without:
```yml
ShopName: armor
DisplayName: Armor+
signs:
  text: '[armor]'
  NeedPermissionToCreateSign: true
shop:
  '1':
    MenuItem:
    - type:BLACK_STAINED_GLASS_PANE
    - amount:1
    - durability:0
    - 'name: '
    RewardType: nothing
    PriceType: nothing
    ExtraPermission: ''
    Message: ''
    InventoryLocation: 1
  '3':
    MenuItem:
    - type:NETHERITE_HELMET
    - amount:1
    RewardType: nothing
    PriceType: nothing
    ExtraPermission: ''
    Message: ''
    InventoryLocation: 3
  '4':
    MenuItem:
    - type:NETHERITE_CHESTPLATE
    - amount:1
    RewardType: nothing
    PriceType: nothing
    ExtraPermission: ''
    Message: ''
    InventoryLocation: 4
  '5':
    MenuItem:
    - type:NETHERITE_LEGGINGS
    - amount:1
    RewardType: nothing
    PriceType: nothing
    ExtraPermission: ''
    Message: ''
    InventoryLocation: 5
  '6':
    MenuItem:
    - type:NETHERITE_BOOTS
    - amount:1
    RewardType: nothing
    PriceType: nothing
    ExtraPermission: ''
    Message: ''
    InventoryLocation: 6
  '7':
    MenuItem:
    - type:NETHERITE_SWORD
    - amount:1
    RewardType: nothing
    PriceType: nothing
    ExtraPermission: ''
    Message: ''
    InventoryLocation: 7
  '9':
    MenuItem:
    - type:BLACK_STAINED_GLASS_PANE
    - amount:1
    - durability:0
    - 'name: '
    RewardType: nothing
    PriceType: nothing
    ExtraPermission: ''
    Message: ''
    InventoryLocation: 9
  '10':
    MenuItem:
    - type:BLACK_STAINED_GLASS_PANE
    - amount:1
    - durability:0
    - 'name: '
    RewardType: nothing
    PriceType: nothing
    ExtraPermission: ''
    Message: ''
    InventoryLocation: 10
  '11':
    MenuItem:
    - type:BLACK_STAINED_GLASS_PANE
    - amount:1
    - durability:0
    - 'name: '
    RewardType: nothing
    PriceType: nothing
    ExtraPermission: ''
    Message: ''
    InventoryLocation: 11
  '12':
    MenuItem:
    - type:BLACK_STAINED_GLASS_PANE
    - amount:1
    - durability:0
    - 'name: '
    RewardType: nothing
    PriceType: nothing
    ExtraPermission: ''
    Message: ''
    InventoryLocation: 12
  '13':
    MenuItem:
    - type:BLACK_STAINED_GLASS_PANE
    - amount:1
    - durability:0
    - 'name: '
    RewardType: nothing
    PriceType: nothing
    ExtraPermission: ''
    Message: ''
    InventoryLocation: 13
  '14':
    MenuItem:
    - type:BLACK_STAINED_GLASS_PANE
    - amount:1
    - durability:0
    - 'name: '
    RewardType: nothing
    PriceType: nothing
    ExtraPermission: ''
    Message: ''
    InventoryLocation: 14
  '15':
    MenuItem:
    - type:BLACK_STAINED_GLASS_PANE
    - amount:1
    - durability:0
    - 'name: '
    RewardType: nothing
    PriceType: nothing
    ExtraPermission: ''
    Message: ''
    InventoryLocation: 15
  '16':
    MenuItem:
    - type:BLACK_STAINED_GLASS_PANE
    - amount:1
    - durability:0
    - 'name: '
    RewardType: nothing
    PriceType: nothing
    ExtraPermission: ''
    Message: ''
    InventoryLocation: 16
  '17':
    MenuItem:
    - type:BLACK_STAINED_GLASS_PANE
    - amount:1
    - durability:0
    - 'name: '
    RewardType: nothing
    PriceType: nothing
    ExtraPermission: ''
    Message: ''
    InventoryLocation: 17
  '18':
    MenuItem:
    - type:BLACK_STAINED_GLASS_PANE
    - amount:1
    - durability:0
    - 'name: '
    RewardType: nothing
    PriceType: nothing
    ExtraPermission: ''
    Message: ''
    InventoryLocation: 18
  '19':
    MenuItem:
    - type:BLACK_STAINED_GLASS_PANE
    - amount:1
    - durability:0
    - 'name: '
    RewardType: nothing
    PriceType: nothing
    ExtraPermission: ''
    Message: ''
    InventoryLocation: 19
  '21':
    MenuItem:
    - type:DIAMOND_HELMET
    - amount:1
    RewardType: nothing
    PriceType: nothing
    ExtraPermission: ''
    Message: ''
    InventoryLocation: 21
  '22':
    MenuItem:
    - type:DIAMOND_CHESTPLATE
    - amount:1
    RewardType: nothing
    PriceType: nothing
    ExtraPermission: ''
    Message: ''
    InventoryLocation: 22
  '23':
    MenuItem:
    - type:DIAMOND_LEGGINGS
    - amount:1
    RewardType: nothing
    PriceType: nothing
    ExtraPermission: ''
    Message: ''
    InventoryLocation: 23
  '24':
    MenuItem:
    - type:DIAMOND_BOOTS
    - amount:1
    RewardType: nothing
    PriceType: nothing
    ExtraPermission: ''
    Message: ''
    InventoryLocation: 24
  '25':
    MenuItem:
    - type:DIAMOND_SWORD
    - amount:1
    RewardType: nothing
    PriceType: nothing
    ExtraPermission: ''
    Message: ''
    InventoryLocation: 25
  '27':
    MenuItem:
    - type:BLACK_STAINED_GLASS_PANE
    - amount:1
    - durability:0
    - 'name: '
    RewardType: nothing
    PriceType: nothing
    ExtraPermission: ''
    Message: ''
    InventoryLocation: 27
```

With:
```yml
ShopName: armor
DisplayName: Armor+
signs: signs
   text: '[armor]'
   NeedPermissionToCreateSign: true
InventoryFill: BLACK_STAINED_GLASS_PANE
shop:
   '3':
     MenuItem:
     - type:NETHERITE_HELMET
     - amount:1
     RewardType: nothing
     PriceType: nothing
     ExtraPermission: ''
     Message: ''
     InventoryLocation: 3
   '4':
     MenuItem:
     - type:NETHERITE_CHESTPLATE
     - amount:1
     RewardType: nothing
     PriceType: nothing
     ExtraPermission: ''
     Message: ''
     InventoryLocation: 4
   '5':
     MenuItem:
     - type:NETHERITE_LEGGINGS
     - amount:1
     RewardType: nothing
     PriceType: nothing
     ExtraPermission: ''
     Message: ''
     InventoryLocation: 5
   '6':
     MenuItem:
     - type:NETHERITE_BOOTS
     - amount:1
     RewardType: nothing
     PriceType: nothing
     ExtraPermission: ''
     Message: ''
     InventoryLocation: 6
   '7':
     MenuItem:
     - type:NETHERITE_SWORD
     - amount:1
     RewardType: nothing
     PriceType: nothing
     ExtraPermission: ''
     Message: ''
     InventoryLocation: 7
   '21':
     MenuItem:
     - type:DIAMOND_HELMET
     - amount:1
     RewardType: nothing
     PriceType: nothing
     ExtraPermission: ''
     Message: ''
     InventoryLocation: 21
   '22':
     MenuItem:
     - type:DIAMOND_CHESTPLATE
     - amount:1
     RewardType: nothing
     PriceType: nothing
     ExtraPermission: ''
     Message: ''
     InventoryLocation: 22
   '23':
     MenuItem:
     - type:DIAMOND_LEGGINGS
     - amount:1
     RewardType: nothing
     PriceType: nothing
     ExtraPermission: ''
     Message: ''
     InventoryLocation: 23
   '24':
     MenuItem:
     - type:DIAMOND_BOOTS
     - amount:1
     RewardType: nothing
     PriceType: nothing
     ExtraPermission: ''
     Message: ''
     InventoryLocation: 24
   '25':
     MenuItem:
     - type:DIAMOND_SWORD
     - amount:1
     RewardType: nothing
     PriceType: nothing
     ExtraPermission: ''
     Message: ''
     InventoryLocation: 25
```
