### ISSUE TITLE
Mmoitems support doesn't work after reload

### ISSUE THREAD

**Issue by OhFoxies** [promcteam/BossShopPro#33]
Hello, I'm using bossshoppro and mmoitems. I have created my shop with instruction provided on MMoitems wiki (https://gitlab.com/phoenix-dvpmt/mmoitems/-/wikis/Supported%20Plugins#bossshoppro).  Buying MMoitems works ONLY after server restart, after using /bossshoppro reload command buying  mmoitems doesn't work anymore - I'm only losing money not getting any item. 
Shop config:
```
shop:
  1:
    PriceType: money
    Price: 15
    RewardType: MMOITEM
    Reward:
    - SWORD.WOODEN_SWORD
    InventoryLocation: 22
```

Version: bossshoppro-2.1.0-20230422.101939-23
Server version: purpur 1.19.4

No erros in console.
Same issue on both spigot and paper
