### ISSUE TITLE
[Suggestion] add a blacklist for items that supports custom named items

### ISSUE THREAD

**Issue by frogglen** [promcteam/BossShopPro#40]
examples

```
  # Example:            (all variables are optional)
  # - Material: STONE
  #   Data: 0
  #   DisplayName: 0
  #   Lore: "Some text that will be searched in every line."
  #   CustomModelData: 0
  #   Compare: IGNORE_CASE      (Default=IGNORE_CASE; STRICT, IGNORE_CASE, CONTAINS, CONTAINS_IGNORE_CASE, REGEX_ANY, REGEX_ALL)
  #
  # Compare examples
  #   STRICT: "FOO" = "FOO"
  #   IGNORE_CASE: "FOO" = "foo"
  #   CONTAINS: "F" is in "Foo"
  #   CONTAINS_IGNORE_CASE: "f" is in "Foo"
  #   REGEX_ANY: "." matches "Foo"
  #   REGEX_ALL: ".*" matches "Foo"
  Blacklist:
  - Material: AIR
    Compare: IGNORE_CASE
  - DisplayName: '&cExample'
    Material: AIR
    Compare: IGNORE_CASE
  - DisplayName: '&5Libro Encantado Élite de'
    Compare: CONTAINS_IGNORE_CASE
  - DisplayName: '&9Chatarra Élite'
    Compare: CONTAINS_IGNORE_CASE
  - DisplayName: '&6Ticket de la Suerte Élite'
    Compare: CONTAINS_IGNORE_CASE
  - Lore: '&7&l&m-------&7<&7&lInfo del Objeto&7>&7&l&m-------'
    Compare: IGNORE_CASE
```
